packages:
  - 'apps/*'
  - 'packages/*'

catalog:
  "@biomejs/biome": "^2.4.14"
  "@tailwindcss/vite": "^4.1.18"
  "@tanstack/devtools-vite": "^0.6.0"
  "@tanstack/history": "^1.161.6"
  "@tanstack/react-devtools": "^0.10.2"
  "@tanstack/react-router": "^1.169.1"
  "@tanstack/react-router-devtools": "^1.166.13"
  "@tanstack/router-plugin": "^1.132.0"
  "@types/node": "^25.6.0"
  "@types/react": "^19.2.14"
  "@types/react-dom": "^19.2.3"
  "@vitejs/plugin-react": "^6.0.1"
  react: "^19.2.5"
  react-dom: "^19.2.5"
  tailwindcss: "^4.1.18"
  typescript: "^6.0.3"
  vite: "^8.0.10"
  vitest: "^4.1.5"
