version: '3.4'

services:
  web:
    image: melodiy-web
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - API_HOST=http://api.melodiy.net/
    ports:
      - 3000:3000
    volumes:
      - ./client/.env.local:/app/.env
  server:
    image: melodiy-server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 5062:5062
    volumes:
      - ./server/appsettings.development.json:/app/appsettings.json
