services:
  server:
    image: melodiy
    build:
      # context: ./
      dockerfile: ./server/Melodiy.Web/Dockerfile
    ports:
      - 5129:5129
    volumes:
      - ./server/Melodiy.Web/appsettings.development.json:/app/appsettings.json
      - ./files:/usr/share/Melodiy
