services:
  web:
    image: melodiy-web
    build:
      context: ./client
      dockerfile: ./apps/web/Dockerfile
      args:
        - API_HOST=http://localhost:5129/
    ports:
      - 4200:80
    volumes:
      - ./client/.env.production:/app/.env
  # web:
  #   image: melodiy-web
  #   build:
  #     context: ./client
  #     dockerfile: Dockerfile
  #     args:
  #       - API_HOST=http://localhost:5129/
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - ./client/.env.production:/app/.env
  server:
    image: melodiy-server
    build:
      context: ./server
      dockerfile: ./Melodiy.Web/Dockerfile
    ports:
      - 5129:5129
    volumes:
      - ./server/Melodiy.Web/appsettings.production.json:/app/appsettings.json
      - ./files:/usr/share/Melodiy
