version: '3.4'

services:
  server:
    image: melodiy-server
    build:
      context: ./server
      dockerfile: ./Melodiy.Api/Dockerfile
    ports:
      - 5041:5041
    volumes:
      - ./server/Melodiy.Api/appsettings.production.json:/app/appsettings.json
