/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as FilesImport } from './routes/files'
import { Route as IndexImport } from './routes/index'
import { Route as PlaylistIdImport } from './routes/playlist/$id'
import { Route as ArtistIdImport } from './routes/artist/$id'

// Create/Update Routes

const FilesRoute = FilesImport.update({
  path: '/files',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PlaylistIdRoute = PlaylistIdImport.update({
  path: '/playlist/$id',
  getParentRoute: () => rootRoute,
} as any)

const ArtistIdRoute = ArtistIdImport.update({
  path: '/artist/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/files': {
      preLoaderRoute: typeof FilesImport
      parentRoute: typeof rootRoute
    }
    '/artist/$id': {
      preLoaderRoute: typeof ArtistIdImport
      parentRoute: typeof rootRoute
    }
    '/playlist/$id': {
      preLoaderRoute: typeof PlaylistIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  FilesRoute,
  ArtistIdRoute,
  PlaylistIdRoute,
])

/* prettier-ignore-end */
