name: Release Melodiy Containers

on:
  workflow_dispatch:
  push:
    tags:
      - v*

env:
  image: ghcr.io/dnyla/melodiy
   
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: ./server/Dockerfile
            image: ghcr.io/dnyla/melodiy-server
            context: ./server
          - dockerfile: ./client/Dockerfile
            image: ghcr.io/dnyla/melodiy-web
            context: ./client
    permissions:
      contents: read
      packages: write

    steps:
      - name: Git Checkout
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ matrix.image }}
        
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.context}}
          file: ${{ matrix.dockerfile }}
          build-args:
            API_HOST="https://api.melodiy.net"
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
